eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  application:
    name: interaction-service

  datasource:
    url: jdbc:postgresql://localhost:5433/interaction_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8084
